### GET test request to example server
GET http://localhost:8080/test

### GET posts from server
GET http://localhost:8080/posts?page=0&size=5&sort=createdAt,desc

### GET post by id from server
GET http://localhost:8080/posts/1

### POST post from server
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "hello2",
  "author": "hhhh",
  "categoryId": 4,
  "password": "@Aaaaaa2",
  "content": ""
}

### POST post from server (Wrong case)
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "",
  "author": "hhhh",
  "password": "@2aaaAa",
  "content": ""
}

### PUT update post from server
PUT http://localhost:8080/posts/2
Content-Type: application/json

{
  "title": "world!",
  "password": "@Aaaaaa2",
  "content": "Oh!good!"
}

### PUT update post from server(Wrong case)
PUT http://localhost:8080/posts/2
Content-Type: application/json

{
  "title": "world!",
  "password": "dddddddd",
  "content": "Oh!good!"
}

### PUT delete post from server
PUT http://localhost:8080/posts/1/delete

### GET comment from post
GET http://localhost:8080/posts/4/comments

### POST comment from post
POST http://localhost:8080/posts/4/comments
Content-Type: application/json

{
  "author": "jeelee",
  "content": "안녕하세요~"
}
### DELETE comment from post
DELETE http://localhost:8080/posts/1/comments/1

### GET CATEGORIES
GET http://localhost:8080/categories

### GET CATEGORY
GET http://localhost:8080/categories/1

### GET COMMENT
GET http://localhost:8080/posts/1/comments

### POST COMMENT
POST http://localhost:8080/posts/9/comments
Content-Type: application/json

{
  "author": "jeelee",
  "content": "hi?!"
}

### DELETE COMMENT
DELETE http://localhost:8080/posts/1/comments/2