### GET test request to example server
GET http://localhost:8080/test

### GET posts from server
GET http://localhost:8080/posts?page=0&size=5&sort=createdAt,desc

### GET post by id from server
GET http://localhost:8080/posts/1

### POST post from server
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "hello",
  "author": "hhhh",
  "password": "@Aaaaaa2",
  "categoryId": 1,
  "content": ""
}

### POST post from server (Wrong case)
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "",
  "author": "hhhh",
  "password": "@2aaaAa",
  "content": ""
}

### PUT update post from server
PUT http://localhost:8080/posts/2
Content-Type: application/json

{
  "title": "world!",
  "password": "@Aaaaaa2",
  "content": "Oh!good!"
}

### PUT update post from server(Wrong case)
PUT http://localhost:8080/posts/2
Content-Type: application/json

{
  "title": "world!",
  "password": "dddddddd",
  "content": "Oh!good!"
}

### PUT delete post from server
PUT http://localhost:8080/posts/4/delete

@Aaaaaa2

### GET CATEGORY
GET http://localhost:8080/category

### GET COMMENT
GET http://localhost:8080/posts/4/comments

### POST COMMENT
POST http://localhost:8080/posts/9/comments
Content-Type: application/json

{
  "author": "jeelee",
  "content": "hi?!"
}

### DELETE COMMENT
DELETE http://localhost:8080/posts/2/comments/2