INSERT INTO CATEGORY (id, name, created_at, updated_at) VALUES (UUID(), '동물', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (id, name, created_at, updated_at) VALUES (UUID(), '식물', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (id, name, created_at, updated_at) VALUES (UUID(), '가족', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (id, name, created_at, updated_at) VALUES (UUID(), '기타', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
