INSERT INTO CATEGORY (name, created_at, updated_at) VALUES ('동물', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (name, created_at, updated_at) VALUES ('식물', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (name, created_at, updated_at) VALUES ('가족', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (name, created_at, updated_at) VALUES ('기타', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
